
CARD_SPACER = 5
CARD_OVERLAP=15

MARKER_SIZE = 10
CARD_LIFE_SPACER = 25

CARD_IMAGE_WIDTH = 81
CARD_IMAGE_HEIGHT = 117
CARD_WIDTH = CARD_IMAGE_WIDTH #50
CARD_HEIGHT = CARD_IMAGE_HEIGHT #100

LIFE_RADIUS = 25
SEAT_WIDTH = (CARD_WIDTH) * 5 + (CARD_SPACER * 4)
SEAT_HEIGHT = CARD_HEIGHT + CARD_LIFE_SPACER + (LIFE_RADIUS * 2)

LIFE_SPACER = (SEAT_WIDTH - ((LIFE_RADIUS * 2) * 5)) / 4