CARD_WIDTH = 50
CARD_HEIGHT = 100
CARD_SPACER = 5
LIFE_RADIUS = 25
LIFE_SPACER = 5
MARKER_SIZE = 10
CARD_LIFE_SPACER = 50

SEAT_WIDTH = (CARD_WIDTH) * 5 + (CARD_SPACER * 4)
SEAT_HEIGHT = CARD_HEIGHT + CARD_LIFE_SPACER + (LIFE_RADIUS * 2)